### PR TITLE
Break infinity loop for terminate the stream thread

### PR DESCRIPTION
**Pull request by sergejkozin-qs**
https://github.com/kubemq-io/kubemq-Python/blob/a87f63e255a2169c2a08166ae6a9234ea97bc591/kubemq/queue/transaction.py#L162

```python
class Transaction(GrpcClient):
    
    ...

    def open_stream(self):
        with self.lock:
            if not self.stream:
                self.stream_observer = Queue()

                def stream():
                    while True:
                        msg = self.stream_observer.get()
                        if msg:
                            yield msg
                            self.stream_observer.task_done()

                def done(call):
                    self.stream = False

                self.inner_stream = self.client.StreamQueueMessage(stream())

                self.inner_stream.add_done_callback(done)
                self.stream = True
                return False
            else:
                return True
```

```python
self.inner_stream = self.client.StreamQueueMessage(stream())
```

*gRPC* spawns the daemon thread when opening a new stream. And `stream()` generator will work into the thread.

When gRPC stream will be terminated (canceled) the daemon thread will stay alive because of `self.stream_observer.get()` is blocking operation and infinity loop inside the `stream()` generator will never finish. 

Over time there will be more and more blocked threads in the memory. Need to break the infinite loop to terminate the daemon thread.

I suggest, to put a specific message to the `stream_observer` Queue and process this in the loop.

```python

class ControlMessages(enum.Enum):
    CLOSE_STREAM = enum.auto()

...

        def stream():
                while True:
                    msg = stream_observer.get()

                    if msg == ControlMessages.CLOSE_STREAM:
                        stream_observer.task_done()
                        break

                    if msg:
                        yield msg
                        stream_observer.task_done()
```

### CODE REVIEW

**Comment by eitam-ring** [comment]
Hi @sergejkozin-qs 
Thanks for the issue founding and the pull request.
Just a small question, any special reason the stream verification changed from if not to if and moved to return true?

**Comment by sergejkozin-qs** [comment]
@eitam-ring, when I investigated the problem before I find the reason - I tried some fixes/refactorings. Actually, this update does not have a special reason. I saved this refactoring in the PR to reduce one indentation level for most of the method code )

@eitam-ring, I can revert this part - PEP8 allows us both approaches, does not matter `if not-else` or `if-return` in this place.

**Comment by eitam-ring** [comment]
HI @sergejkozin-qs 
Thanks for the explanation.
We are reviewing the pull request.
Will keep you updated

**Comment by eitam-ring** [comment]
@sergejkozin-qs 
Hi ,
We have merged the changes, thanks for the input

**Pull request merged**
